  char-fe:
    build: ./chat-fe
    environment:
      NODE_ENV: production
    ports:
      - "80:80"
    links:
      - chat-be
  chat-be:
    build: .
    environment:
      NODE_ENV: production
    ports:
      - "3000"
      - "3001"
    links:
      - chat-redis
  chat-redis:
    image: redis:latest
    ports:
      - "6379"
