  char-fe:
    image: quay.io/d3lirium/chat-fe
    environment:
      NODE_ENV: production
    ports:
      - "80:80"
    links:
      - chat-be
  chat-be:
    image: quay.io/d3lirium/chat-be
    environment:
      NODE_ENV: production
    ports:
      - "3000"
      - "3001"
    links:
      - chat-redis
  chat-redis:
    image: redis:latest
    ports:
      - "6379"
