module.exports = {
  MESSAGE: 'MESSAGE',
  MESSAGES: 'MESSAGES',
  SOMEONE_HAS_STOP_TYPING: 'SOMEONE_HAS_STOP_TYPING',
  SOMEONE_IS_TYPING: 'SOMEONE_IS_TYPING',
  STOP_TYPING: 'STOP_TYPING',
  TYPING: 'TYPING',
  USER: 'USER',
  USERS: 'USERS'
};
